# Site settings
author: awesome-writer-4373
title: 
header-img: img/home-bg.png
email: hectoraperez1999@gmail.com
copyright_name: awesome-writer-4373
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hector2-cloud

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
